//! Value construction and access to generated event interfaces.
use crate::Sharded;
use crate::{InvokeError, ShardAffinity, ShardBinding, ShardRcHandle};
use std::sync::Arc;

/// A value's event interface and shard affinity.
pub trait Eventful {
    /// Generated signal storage shared by the value and its handles.
    type EventSetType: ?Sized + Send + Sync + 'static;
    /// Named destination or [`crate::DynamicShard`] for runtime binding.
    type Shard: ShardAffinity;

    /// Construct on the designated shard and return a thread-safe handle.
    /// Only the factory's captures must be Send; Self may contain Rc or RefCell.
    /// The designated event loop must be running to complete this operation.
    /// See the [quick start](crate#quick-start).
    ///
    /// # Errors
    /// Returns [`InvokeError`] on shutdown, cancellation, invalid affinity, or
    /// an unwinding factory panic.
    ///
    /// # Panics
    /// Panics if initializing the named backend fails.
    fn spawn<F>(
        factory: F,
    ) -> impl Future<Output = Result<ShardRcHandle<Self>, InvokeError>> + Send + 'static
    where
        Self: Sized + HasEvents<Self::EventSetType> + 'static,
        Self::Shard: ShardBinding,
        F: FnOnce() -> Self + Send + 'static,
    {
        Self::Shard::handle().bind_async(move |bind| bind(factory()).to_handle())
    }
}

/// Access the event storage generated by [`crate::eventful`].
pub trait HasEvents<E>
where
    E: ?Sized + Send + 'static,
{
    /// Borrow the shared event interface.
    fn events(&self) -> &Arc<E>;
}
