[workspace]
members = [
    "eventful-rs",
    "eventful-rs-macros",
    "examples/no-main-shard",
    "examples/tokio",
    "examples/sharded-main",
    "examples/targeted-events",
    "examples/connect-all",
]
resolver = "3"

[workspace.package]
authors = ["eventful-rs contributors"]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
