[package]
name = "eventful-rs"
version = "0.1.0"
edition = "2024"

[features]
tokio = ["dep:tokio"]
slint = ["dep:slint"]

[dependencies]
eventful-rs-macros = { path = "../eventful-rs-macros" }
tokio = { version = "1.53.1", features = [
    "sync",
    "rt-multi-thread",
], optional = true }
slint = { version = "1.17.1", optional = true }
