[package]
name = "eventful-rs"
version = "0.1.0"
edition = "2024"

[features]
default = ["tokio", "slint"]
tokio = ["dep:tokio"]
slint = ["dep:slint"]

[dependencies]
eventful-rs-macros = { path = "../eventful-rs-macros" }
futures = "0.3"
tokio = { version = "1", features = [
    "sync",
    "rt-multi-thread",
], optional = true }
slint = { version = "1.17.1", optional = true }
